// Posiciones de candidatos por tema (escala 1-5)
// 1 = Izquierda/Progresista, 5 = Derecha/Conservador, 3 = Centro
// Estas posiciones se basan en declaraciones publicas y planes de gobierno

export interface CandidatePosition {
  candidateId: string
  candidateName: string
  candidateSlug: string
  partyName: string
  photoUrl?: string
  positions: Record<string, number>
}

export const CANDIDATE_POSITIONS: CandidatePosition[] = [
  {
    candidateId: 'keiko-fujimori',
    candidateName: 'Keiko Fujimori',
    candidateSlug: 'keiko-fujimori',
    partyName: 'Fuerza Popular',
    photoUrl: undefined,
    positions: {
      security: 5,
      economy: 5,
      education: 4,
      health: 4,
      mining: 5,
      pensions: 4,
      corruption: 4,
      decentralization: 4,
      foreign_policy: 5,
      political_reform: 5,
    },
  },
  {
    candidateId: 'antauro-humala',
    candidateName: 'Antauro Humala',
    candidateSlug: 'antauro-humala-tasso',
    partyName: 'Frente Patriotico',
    photoUrl: undefined,
    positions: {
      security: 5,
      economy: 1,
      education: 1,
      health: 1,
      mining: 2,
      pensions: 1,
      corruption: 1,
      decentralization: 1,
      foreign_policy: 1,
      political_reform: 1,
    },
  },
  {
    candidateId: 'cesar-acuna',
    candidateName: 'Cesar Acuna',
    candidateSlug: 'cesar-acuna-peralta',
    partyName: 'Alianza para el Progreso',
    photoUrl: undefined,
    positions: {
      security: 4,
      economy: 4,
      education: 4,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 3,
      decentralization: 2,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'hernando-de-soto',
    candidateName: 'Hernando de Soto',
    candidateSlug: 'hernando-de-soto-polar',
    partyName: 'Avanza Pais',
    photoUrl: undefined,
    positions: {
      security: 3,
      economy: 5,
      education: 5,
      health: 4,
      mining: 5,
      pensions: 5,
      corruption: 3,
      decentralization: 3,
      foreign_policy: 5,
      political_reform: 4,
    },
  },
  {
    candidateId: 'daniel-urresti',
    candidateName: 'Daniel Urresti',
    candidateSlug: 'daniel-urresti-elera',
    partyName: 'Podemos Peru',
    photoUrl: undefined,
    positions: {
      security: 5,
      economy: 3,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 3,
      political_reform: 3,
    },
  },
  {
    candidateId: 'veronika-mendoza',
    candidateName: 'Veronika Mendoza',
    candidateSlug: 'veronika-mendoza-frisch',
    partyName: 'Juntos por el Peru',
    photoUrl: undefined,
    positions: {
      security: 2,
      economy: 1,
      education: 1,
      health: 1,
      mining: 1,
      pensions: 1,
      corruption: 2,
      decentralization: 1,
      foreign_policy: 1,
      political_reform: 1,
    },
  },
  {
    candidateId: 'rafael-lopez-aliaga',
    candidateName: 'Rafael Lopez Aliaga',
    candidateSlug: 'rafael-lopez-aliaga',
    partyName: 'Renovacion Popular',
    photoUrl: undefined,
    positions: {
      security: 5,
      economy: 5,
      education: 5,
      health: 5,
      mining: 5,
      pensions: 5,
      corruption: 5,
      decentralization: 4,
      foreign_policy: 5,
      political_reform: 5,
    },
  },
  {
    candidateId: 'george-forsyth',
    candidateName: 'George Forsyth',
    candidateSlug: 'george-forsyth-sommer',
    partyName: 'Victoria Nacional',
    photoUrl: undefined,
    positions: {
      security: 4,
      economy: 4,
      education: 3,
      health: 3,
      mining: 4,
      pensions: 3,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 4,
      political_reform: 3,
    },
  },
  {
    candidateId: 'julio-guzman',
    candidateName: 'Julio Guzman',
    candidateSlug: 'julio-guzman-caceres',
    partyName: 'Partido Morado',
    photoUrl: undefined,
    positions: {
      security: 3,
      economy: 3,
      education: 2,
      health: 2,
      mining: 3,
      pensions: 3,
      corruption: 2,
      decentralization: 2,
      foreign_policy: 3,
      political_reform: 2,
    },
  },
  {
    candidateId: 'yonhy-lescano',
    candidateName: 'Yonhy Lescano',
    candidateSlug: 'yonhy-lescano-ancieta',
    partyName: 'Accion Popular',
    photoUrl: undefined,
    positions: {
      security: 3,
      economy: 2,
      education: 2,
      health: 2,
      mining: 2,
      pensions: 2,
      corruption: 2,
      decentralization: 2,
      foreign_policy: 2,
      political_reform: 2,
    },
  },
  {
    candidateId: 'alberto-beingolea',
    candidateName: 'Alberto Beingolea',
    candidateSlug: 'alberto-beingolea-delgado',
    partyName: 'Partido Popular Cristiano',
    photoUrl: undefined,
    positions: {
      security: 4,
      economy: 4,
      education: 4,
      health: 3,
      mining: 4,
      pensions: 4,
      corruption: 4,
      decentralization: 3,
      foreign_policy: 4,
      political_reform: 4,
    },
  },
  {
    candidateId: 'jose-vega',
    candidateName: 'Jose Vega Antonio',
    candidateSlug: 'jose-vega-antonio',
    partyName: 'Union por el Peru',
    photoUrl: undefined,
    positions: {
      security: 4,
      economy: 2,
      education: 2,
      health: 2,
      mining: 2,
      pensions: 2,
      corruption: 2,
      decentralization: 2,
      foreign_policy: 2,
      political_reform: 2,
    },
  },
]

// Funcion para obtener posicion de candidato por tema
export function getCandidatePosition(candidateSlug: string, topic: string): number | null {
  const candidate = CANDIDATE_POSITIONS.find(c => c.candidateSlug === candidateSlug)
  return candidate?.positions[topic] ?? null
}
